{
 "title": "System Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Network Metrics",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "Total Received Packets"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "Total Transmitted Packets"
    }
   ]
  },
  {
   "title": "System RAM Information",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / 1024 ^ 3",
     "legendFormat": "Total RAM"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 ^ 3",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 ^ 3",
     "legendFormat": "RAM Available"
    }
   ]
  },
  {
   "title": "Swap Memory metrics",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes / 1024^3",
     "legendFormat": "Total Swap Memory"
    },
    {
     "expr": "node_memory_SwapFree_bytes / 1024 ^ 3",
     "legendFormat": "Free Swap Memory"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / 1024 ^ 3",
     "legendFormat": "Used Total Swap Memory"
    }
   ]
  },
  {
   "title": "Clients Connected To Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(emqx_client_connected[$__rate_interval])",
     "legendFormat": "Clients Connected"
    }
   ]
  },
  {
   "title": "EMQX Messages activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(emqx_messages_publish[$__rate_interval])",
     "legendFormat": "Messages published on broker"
    },
    {
     "expr": "rate(emqx_messages_received[$__rate_interval])",
     "legendFormat": "Total messages received "
    }
   ]
  },
  {
   "title": "EMQX NODE HEALTHY",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emqx_cluster_nodes_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_up{device=\"enp2s0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EMQX User activity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emqx_subscribers_count", "legendFormat": "Total Subscribers" },
    {
     "expr": "rate(emqx_packets_sent[$__rate_interval])",
     "legendFormat": "EMQX Packets Received"
    },
    {
     "expr": "rate(emqx_packets_sent[$__rate_interval])",
     "legendFormat": "Total Packets sent"
    }
   ]
  }
 ]
}